# set hosted runner test & deployment

name: Deployment

# on:
#   push:
#     branches:
#       - main

on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: self-hosted

    steps:
      - name: Git clone repository
        uses: actions/checkout@v7

      - name: install node
        uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: install packages
        run: npm install

      - name: run test
        run: npm run check

      - name: Run tests and save results
        run: |
          mkdir -p test-results
          npm run check | tee test-results/test-results.txt

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/test-results.txt

  Deploy:
    needs: Test
    runs-on: self-hosted

    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: downloaded-results

      - name: Display test results
        run: |
          echo "=== Test Results ==="
          cat downloaded-results/test-results.txt

      - name: ssh private server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Deploy to Private Server
        run: |
          cd ~
          sudo apt update && sudo apt upgrade -y
          mkdir project && cd project
          git clone https://github.com/S999Y/CI-CD-GitHub-actions.git

      - name: Deploy to Private Server
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_ADDRESS }} << 'EOF'

          echo "Updating server..."
          sudo apt update -y
          echo "Checking Node.js..."

          if ! command -v node >/dev/null 2>&1
          then

          echo "Node.js not found. Installing Node.js 24..."
          curl -fsSL https://deb.nodesource.com/setup_24.x | sudo -E bash -

          sudo apt install -y nodejs
          else
            echo "Node already installed"
          fi

          echo "Node version:"
          node -v

          echo "NPM version:"
          npm -v

          echo "Preparing project directory..."

          mkdir -p ~/project
          cd ~/project

          echo "Removing old deployment..."
          rm -rf CI-CD-GitHub-actions

          echo "Cloning repository..."

          git clone https://github.com/S999Y/CI-CD-GitHub-actions.git

          cd CI-CD-GitHub-actions

          echo "Installing dependencies..."
          npm install

          echo "Deployment completed successfully"
          EOF
